"""
PlatformIO `pre:` extra_script that composes the web UI sources in `web/`
into `src/generated/webpages.h` -- a set of PROGMEM string constants, one
per page template in `web/pages/`.

This MUST run at import time (registered as
`pre:scripts/generate_webpages.py`, not via env.AddPreAction) so the
generated header exists before PlatformIO scans #include dependencies --
otherwise a clean checkout would fail to build on the first try.

Bun (web/dev-server.ts) is only used for local page development in a
browser; it is never required to build the firmware.
"""

import gzip
import os
import re
from pathlib import Path

Import("env")  # noqa: F821 -- injected by PlatformIO

PROJECT_DIR = Path(env["PROJECT_DIR"])
WEB_DIR = PROJECT_DIR / "web"
PAGES_DIR = WEB_DIR / "pages"
ASSETS_DIR = WEB_DIR / "assets"
OUTPUT_FILE = PROJECT_DIR / "src" / "generated" / "webpages.h"

# Assets served as their own gzip'd HTTP routes (see src/webserverHelper.h),
# rather than inlined into page templates via @include. Unlike pages, these
# have no runtime %PLACEHOLDER% substitution, so they can be compressed once
# at build time.
GZIPPED_ASSET_EXTENSIONS = (".css", ".js")

# Matches a line that is *only* an include directive, e.g.
#   <!-- @include partials/head.html -->
# Paths are resolved relative to web/ (WEB_DIR), regardless of which file
# contains the directive.
INCLUDE_RE = re.compile(r"^\s*<!--\s*@include\s+(\S+)\s*-->\s*$")


def _display(path: Path) -> str:
    """Best-effort path for error messages -- relative to web/ if possible."""
    try:
        return str(path.resolve().relative_to(WEB_DIR.resolve()))
    except ValueError:
        return str(path)


def resolve_includes(path: Path, stack=()):
    """Recursively resolve @include directives in `path`, returning the
    fully composed text. `stack` tracks the current include chain so
    circular includes raise a clear error instead of recursing forever."""
    if any(path.resolve() == p.resolve() for p in stack):
        chain = " -> ".join(_display(p) for p in (*stack, path))
        raise RuntimeError(f"generate_webpages.py: circular @include detected: {chain}")

    if not path.is_file():
        including = _display(stack[-1]) if stack else "<root>"
        raise RuntimeError(
            f"generate_webpages.py: @include target not found: "
            f"{_display(path)} (included from {including})"
        )

    text = path.read_text(encoding="utf-8")
    out_lines = []
    for line in text.splitlines(keepends=True):
        match = INCLUDE_RE.match(line)
        if match:
            include_path = WEB_DIR / match.group(1)
            out_lines.append(resolve_includes(include_path, stack + (path,)))
        else:
            out_lines.append(line)
    return "".join(out_lines)


def symbol_name(page_path: Path) -> str:
    """config-save.html -> page_config_save"""
    return "page_" + page_path.stem.replace("-", "_")


def asset_symbol_name(asset_path: Path) -> str:
    """style.css -> asset_style_css_gz"""
    return "asset_" + asset_path.name.replace(".", "_").replace("-", "_") + "_gz"


def wrap_progmem(name: str, content: str) -> str:
    """Wrap `content` in a PROGMEM raw-string literal, picking a delimiter
    that can't collide with the closing `)<delim>"` sequence appearing
    inside the (already-composed) content."""
    delimiter = "====="
    while f")" + delimiter in content:
        delimiter += "="
    return f'constexpr char {name}[] PROGMEM = R"{delimiter}(\n{content}\n){delimiter}";\n\n'


def wrap_progmem_gzip_bytes(name: str, raw_bytes: bytes) -> str:
    """Gzip `raw_bytes` and emit it as a `uint8_t[] PROGMEM` byte array plus
    a matching `_len` constant. Used for static assets (CSS/JS) that have no
    runtime %PLACEHOLDER% substitution, so they can be compressed once here
    rather than on every request. `mtime=0` keeps the output byte-for-byte
    reproducible across builds regardless of when they run."""
    compressed = gzip.compress(raw_bytes, compresslevel=9, mtime=0)
    hex_bytes = ", ".join(f"0x{b:02x}" for b in compressed)
    out = f"constexpr uint8_t {name}[] PROGMEM = {{{hex_bytes}}};\n"
    out += f"constexpr size_t {name}_len = {len(compressed)};\n\n"
    return out


def generate():
    if not PAGES_DIR.is_dir():
        raise RuntimeError(f"generate_webpages.py: pages directory not found: {PAGES_DIR}")

    page_files = sorted(PAGES_DIR.glob("*.html"))
    if not page_files:
        raise RuntimeError(f"generate_webpages.py: no *.html page templates found in {PAGES_DIR}")

    asset_files = sorted(
        f for f in ASSETS_DIR.glob("*") if f.suffix in GZIPPED_ASSET_EXTENSIONS
    )

    chunks = [
        "#pragma once\n\n",
        "// AUTO-GENERATED -- DO NOT EDIT\n",
        "// Generated by scripts/generate_webpages.py from web/ sources.\n",
        "// Re-run `pio run` (or edit web/ and rebuild) to regenerate.\n\n",
    ]

    for page_file in page_files:
        composed = resolve_includes(page_file)
        chunks.append(wrap_progmem(symbol_name(page_file), composed))

    for asset_file in asset_files:
        raw_bytes = asset_file.read_bytes()
        chunks.append(wrap_progmem_gzip_bytes(asset_symbol_name(asset_file), raw_bytes))

    new_content = "".join(chunks)

    if OUTPUT_FILE.is_file() and OUTPUT_FILE.read_text(encoding="utf-8") == new_content:
        # Byte-identical -- skip the write so incremental builds don't
        # see a changed mtime and recompile everything that includes it.
        return

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(new_content, encoding="utf-8")
    print(f"generate_webpages.py: wrote {os.path.relpath(OUTPUT_FILE, PROJECT_DIR)}")


generate()
